### ISSUE TITLE
HM_GB_TOOLS_PATH isn't defined

### ISSUE THREAD

**Issue by johnbillion** [humanmade/hm-gutenberg-tools#1]
The `HM_GB_TOOLS_PATH` constant is used in `HM\GutenbergTools\enqueue_block_editor_assets()`, but it isn't defined anywhere.

**Comment by mattheu** [comment]
Thanks @johnbillion. Fixed in https://github.com/humanmade/hm-gutenberg-tools/commit/7b94d77b5abd83e1209fb80d1355ff1b3105013e.
