### ISSUE TITLE
ReferenceError: hm is not defined

### ISSUE THREAD

**Issue by soniapello** [humanmade/hm-gutenberg-tools#10]
Hi
I try to use your postselectbutton component like this:
```
const { __ } = wp.i18n; // Import __() from wp.i18n
const { registerBlockType } = wp.blocks; // Import registerBlockType() from wp.blocks
const { PostSelectButton } = hm.components;
```
and then I use it in edit:
```
edit: function( props ) {
		// Creates a <p class='wp-block-gb-basic-esnext-02'></p>.
		return (
			<PostSelectButton 
			    value={ value }
			    onSelect={ value => setAttributes( { value } ) }
			    postType="post" 
			    btnProps={ { isLarge: true } }
			/>
		);
	},
```
but it gives me ReferenceError: hm is not defined
I thought that hm were install globally when I activate your plugin.

**Comment by kucrut** [comment]
The generated assets are not included in this repo, so you will need to build them first by running `yarn && yarn build`. See https://github.com/humanmade/hm-gutenberg-tools/issues/8#issuecomment-361904198

**Comment by soniapello** [comment]
@kucrut I've used npm install && npm run build insted like mattheu said .

**Comment by kucrut** [comment]
@soniapello Can you make sure that the script are actually loaded? Take a look at the Network tab of devtools and see if there are 404 requests in there.

**Comment by soniapello** [comment]
The script are  loaded
<img width="576" alt="ima" src="https://user-images.githubusercontent.com/20027271/35807037-cca3a3da-0a81-11e8-9071-1e1a9f1d915f.png">
but I guess I don't use it properly.

**Comment by mattheu** [comment]
Ah - when enqueuing the script that makes use of `window.hm`, can you make sure you specify `hm-gb-tools-editor` as a dependency? I think I need to update the usage instructions to include this line.

That should make sure `window.hm` is available when you try to use it.

**Comment by soniapello** [comment]
try it with this 
array( 'wp-blocks', 'wp-i18n', 'wp-element','hm-gb-tools-editor' ) for js and this for css
array( 'wp-edit-blocks','hm-gb-tools-editor' ) and get 
ReferenceError: value is not defined

**Comment by mattheu** [comment]
Would you be able to share your code? That error sounds like this is loading correctly now, but there is an error in your JS.

**Comment by soniapello** [comment]
Here the [link](https://files.fm/u/2br73mkd)
I use gutenberg example [plugin](https://github.com/WordPress/gutenberg-examples) and create **_02-esnext_** folder to use postselectbutton

**Comment by mattheu** [comment]
OK I see the problem. My sample code didn't include everything you need around it.

* Firstly, you should register your attribtute. Lets call it `myAttr`
* You'll see that `props` is the passed into the edit function. The attribute values are passed as `props.attributes`. All registered attributes will be included, and you can specify both a default value and a type. e.g. if you specify string it will ensure it is always a string.
* Access your prop value like this: `props.attributes.myAttr`
* `setAttributes` is also a property of `props`. So you'll need to call `props.setAttributes`.
* I simplified the code for setAttributes a bit, but I'll write it a bit more verbose way below.
* Since you're using ES6, you could take this all a little further and destructure `props` as part of the edit function params.

You'll end up with something like this (note it is untested)

```js
/**
 * BLOCK: Basic with ESNext
 *
 * Registering a basic block with Gutenberg.
 * Simple block, renders and saves the same content without any interactivity.
 *
 * Using inline styles - no external stylesheet needed.  Not recommended!
 * because all of these styles will appear in `post_content`.
 */

const { registerBlockType } = wp.blocks; // Import registerBlockType() from wp.blocks
const { PostSelectButton } = hm.components;

registerBlockType( 'gb/esnext-02', { // Block name. Block names must be string that contains a namespace prefix. Example: my-plugin/my-custom-block.
    title: 'popote',// Block title.
    icon: 'shield', // Block icon from Dashicons → https://developer.wordpress.org/resource/dashicons/.
    category: 'common', // Block category — Group blocks together based on common traits E.g. common, formatting, layout widgets, embed.

    attributes: {
        myAttr: { type: 'string' }
    },

    edit: function( { attributes, setAttributes } ) {
        return (
            <PostSelectButton
                value={ attributes.myAttr }
                onSelect={ newValue => setAttributes( { myAttr: newValue } ) }
                postType="post"
                btnProps={ { isLarge: true } }
            />
        );
    },

    // The "save" property must be specified and must be a valid function.
    save: function( props ) {
        return (
            <p className={ props.className }>Hello World! — from the frontend (02 Basic Block ESNext).</p>
        );
    },
} );

```

**Comment by soniapello** [comment]
It works but I can select only one post. From what I understand myAttr is the id of the post selected. Is it possible to select multiple posts by changing the myAttr's type in array ?
I also try to get back the myAttr result with this code :
```
const { __ } = wp.i18n;
const { registerBlockType } = wp.blocks; // Import registerBlockType() from wp.blocks
const { PostSelectButton } = hm.components;

registerBlockType( 'gb/esnext-02', { // Block name. Block names must be string that contains a namespace prefix. Example: my-plugin/my-custom-block.
    title: 'popote',// Block title.
    icon: 'shield', // Block icon from Dashicons → https://developer.wordpress.org/resource/dashicons/.
    category: 'common', // Block category — Group blocks together based on common traits E.g. common, formatting, layout widgets, embed.

    attributes: {
        myAttr: { type: 'string' }
    },


    edit( { attributes, setAttributes } ) {

         const { myAttr } = attributes;
         function onSelectContent( newValue ) {
            setAttributes( { myAttr: newValue } );
        }
        return (
            <PostSelectButton
                value={ myAttr }
                onSelect={ onSelectContent }
                postType="post"
                btnProps={ { isLarge: true } }
            >{ __( 'Button text' ) }
	    </PostSelectButton>

        );
    },

  save( { attributes } ) {
        const { myAttr } = attributes;

        return <span>{ myAttr }</span>;
    },
} );

**Comment by mattheu** [comment]
You can pass the prop `maxPosts` and specify a number. Apologies - the documentation is still a work in progress.

**Comment by soniapello** [comment]
Thanks you for your help. I guess I will stop asking you questions cause you'll spend too much time with me and have less time for making the documentation :-D
