### ISSUE TITLE
Post Selection Button: hm not defined

### ISSUE THREAD

**Issue by bdrutl** [humanmade/hm-gutenberg-tools#39]
In Gutenberg 4.5.1 

const { PostSelectButton } = hm.components;

is leading to "Uncaught ReferenceError: hm is not defined". Have HM Gutenberg tools installed and activated as a plugin.

Please advise thanks so much

**Comment by kadamwhite** [comment]
I'm unable to replicate this and, regrettably, it has been three years since this issue got opened. I am going to close on the assumption that if it was an issue then, it has been resolved since.
