### ISSUE TITLE
filemtime warning 

### ISSUE THREAD

**Issue by robbisy** [humanmade/hm-gutenberg-tools#8]
Hi Matthew I install hm-gutenberg-tools as plugin and I get filemtime warnings

**Comment by mattheu** [comment]
I'm not including the compiled JS and CSS in the github repo. You need to build this by running the following: 

`yarn && yarn build`

If you don't have yarn you can probably just do:

`npm install && npm run build`

I'll make sure I update the documentation. I think that I might need to include built files on the master branch to prevent this being an issue for people in future. However if built files are included for development branches, they quickly become a bit of a nightmare with merge conflicts!

**Comment by robbisy** [comment]
OK and if I use postselectbutton in a block 
Is there a way to use it as a dependency for the block like hm which can be add to the array:
```
wp_enqueue_script(
		'gb-block-02-basic-esnext', // Handle.
		plugins_url( 'block.build.js', __FILE__ ), 
		array( 'wp-blocks', 'wp-i18n', 'wp-element','hm'), // hm Dependency.
		filemtime( plugin_dir_path( __FILE__ ) . 'block.js' ) //
	);
```
